In [45]:
# Creating Array in numpy
import numpy as np
import math
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])
num1 = 10
num2 = 12
print(arr)

[1 2 3 4 5 6 7]


In [11]:
# Operations in Numpy Array
## Binary Operations : Acts on bits and performsbit by bit operations
print("Input number 1 is:", num1)
print("Input number 2 is:", num2)
out_num1 = np.bitwise_and(num1, num2)
out_num2 = np.bitwise_or(num1, num2)
out_num3 = np.bitwise_xor(num1, num2)
out_num4 = np.invert(num1)
print("Bitwise AND OPeration is:", out_num1)
print("Bitwise OR OPeration is:", out_num2)
print("Bitwise XOR OPeration is:", out_num3)
print("Bitwise inversion OPeration is:", out_num4)

Input number 1 is: 10
Input number 2 is: 12
Bitwise AND OPeration is: 8
Bitwise OR OPeration is: 14
Bitwise XOR OPeration is: 6
Bitwise inversion OPeration is: -11


In [29]:
# Numpy Mathematical Functions
## Trigonometric Functions
sine_values = np.sin(arr1) # gives sin value
print(sine_values)
cosine_values = np.cos(arr1) # gives cos value
print(cosine_values)
inv_sin = np.arcsin(sine_values) # gives sin inverse
print(inv_sin)
inv_cos = np.arccos(cosine_values) # gives cos inverse
print(inv_cos)
log_fun = np.log(arr1) #Log Function
print(log_fun)
cube_root = np.cbrt(num1) #Cube Root
print(cube_root)
clipping = np.clip(arr1, a_min = 2, a_max=4)
print(clipping)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225]
[ 1.          1.14159265  0.14159265 -0.85840735 -1.28318531 -0.28318531
  0.71681469]
[1.         2.         3.         2.28318531 1.28318531 0.28318531
 0.71681469]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]
2.154434690031884
[2 2 3 4 4 4 4]


In [31]:
arr1.size

7

In [61]:
# Arthematic Operations
arr2 = arr2.reshape(1,7)
print(np.add(arr1,arr2)) # Adding array
print(np.subtract(arr1,arr2)) # Subtract Array
print(np.multiply(arr1,arr2)) # Multiply Array
print(np.divide(arr1, arr2)) # Divide Array
print(np.power(arr1,2)) # Power to 2
print(np.sum(arr1)) # sum of arr1
print(np.inner(arr1,arr2)) # Computes inner product


[[ 9 11 13 15 17 19 21]]
[[-7 -7 -7 -7 -7 -7 -7]]
[[ 8 18 30 44 60 78 98]]
[[0.125      0.22222222 0.3        0.36363636 0.41666667 0.46153846
  0.5       ]]
[ 1  4  9 16 25 36 49]
28
[336]


In [65]:
## Matrix
x = np.array([[1, 2], [4, 5]]) 
y = np.array([[7, 8], [9, 10]]) 
print (np.add(x,y)) # matrix add
print (np.subtract(x,y)) # matrix subtract
print (np.divide(x,y)) # matrix divide
print (np.multiply(x,y)) # element-wise multiply
print (np.dot(x,y)) # dot product


[[ 8 10]
 [13 15]]
[[-6 -6]
 [-5 -5]]
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
[[ 7 16]
 [36 50]]
[[25 28]
 [73 82]]


In [69]:
res = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        res[i][j] = x[i][j] + y[i][j]

for r in res:
    print(r)

[8, 10, 0]
[13, 15, 0]
[0, 0, 0]


In [87]:
trans=x.transpose() # transpose of matrix
print(trans)
print(x.var()) # variance of matrix
print(np.linalg.inv(x)) # inverse of matrix
print(np.linalg.det(x)) # Determinant of matrix
print(np.linalg.matrix_rank(x)) # Rank of matrix
print(np.trace(x)) # trace of matrix
print(np.linalg.eigh(x)) # Eigen VAlue

[[1 4]
 [2 5]]
2.5
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
-2.9999999999999996
2
6
EighResult(eigenvalues=array([-1.47213595,  7.47213595]), eigenvectors=array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]]))


In [107]:
import pandas as pd
df = pd.DataFrame(x, columns=['A','B']) # Creating Data Frame from np.array
print(df)
ser = pd.Series(arr1) # Pandas Series
print(ser)
print(ser[:4]) # Accessing element of series
print(ser.loc[3:6]) # Accessing explicit index
print(ser.iloc[3:6]) # Accessing inplicit index
print(df.head()) 

   A  B
0  1  2
1  4  5
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32
0    1
1    2
2    3
3    4
dtype: int32
3    4
4    5
5    6
6    7
dtype: int32
3    4
4    5
5    6
dtype: int32
   A  B
0  1  2
1  4  5


In [115]:
df = pd.read_csv(r"C:\Users\acer\Downloads\friends_episodes_v2.csv")
df.head()

Year_of_prod  Season                                   Episode_Title  \
0          1994       1            The One with the Sonogram at the End   
1          1994       1                          The One with the Thumb   
2          1994       1              The One with George Stephanopoulos   
3          1994       1  The One with the East German Laundry Detergent   
4          1994       1                           The One with the Butt   

   Duration                                            Summary  \
0        22  Ross finds out his ex-wife is pregnant. Rachel...   
1        22  Monica becomes irritated when everyone likes h...   
2        22  Joey and Chandler take Ross to a hockey game t...   
3        22  Eager to spend time with Rachel, Ross pretends...   
4        22  Monica's obsessiveness is put to the test afte...   

         Director  Stars  Votes  
0   James Burrows    8.1   4888  
1   James Burrows    8.2   4605  
2   James Burrows    8.1   4468  
3   Pamela Fryman    8.5   4438  
4  Arlene Sanford    8.1   4274